$script = <<-SCRIPT
yum install epel-release -y 
yum update -y
yum install  -y net-tools wget 
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y  docker-ce docker-ce-cli containerd.io
echo "192.168.1.34 openshift.local"  >> /etc/hosts
systemctl start docker
systemctl enable docker
cp /home/vagrant/daemon.json /etc/docker/daemon.json
systemctl daemon-reload
systemctl restart docker
cd /home/vagrant
wget  https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz
tar -xvf /home/vagrant/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit.tar.gz
export PATH=$PATH:/home/vagrant/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit
/home/vagrant/openshift-origin-server-v3.11.0-0cbc58b-linux-64bit/oc cluster up --public-hostname=openshift.local --routing-suffix=192.168.1.34.nip.io
SCRIPT

Vagrant.configure("2") do |config|  
  config.vm.define "okd" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.network "public_network", ip: "192.168.1.34", bridge: "en0: Wi-Fi (Wireless)"
    subconfig.vm.hostname = 'okd.local'
    subconfig.vm.provision "file", source: "./daemon.json", destination: "/home/vagrant/daemon.json"
    subconfig.vm.provision "shell", inline:$script
    subconfig.disksize.size = '50GB'
    subconfig.vm.provider "virtualbox" do |v|
       v.memory = 4096
       v.cpus = 2
    end      
  end
end
